apiVersion: apps/v1
kind: Deployment
metadata:
  name: publitech-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publitech-auth-service
  template:
    metadata:
      labels:
        app: publitech-auth-service
    spec:
      containers:
        - image: karthik496/publitech-auth-service:latest
          name: publitech-auth-service
          envFrom:
            - configMapRef:
                name: auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: publitech-auth-service
spec:
  selector:
    app: publitech-auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
 