apiVersion: apps/v1
kind: Deployment
metadata:
  name: publitech-notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publitech-notification-service
  template:
    metadata:
      labels:
        app: publitech-notification-service
    spec:
      containers:
        - image: karthik496/publitech-notification-service
          name: publitech-notification-service
          envFrom:
            - configMapRef:
                name: notification-config
---
apiVersion: v1
kind: Service
metadata:
  name: publitech-notification-service
spec:
  selector:
    app: publitech-notification-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
 